### ISSUE TITLE
🎃🍂 remove .gitignore'd files from the repo

### ISSUE THREAD

**Issue by choyiny** [choyiny/factorizing-semiprimes#12]
Right now the IDE project files still exist in the repo. The goal of this issue is to remove the excess files from the repo.

**Comment by andreybleme** [comment]
@choyiny Hello! I can help with this one. You can assign it to me? :+1: 

I'm on it.

**Comment by choyiny** [comment]
@andreybleme someone opened a PR for it, sorry! You could perhaps review the code style?

**Comment by andreybleme** [comment]
@choyiny sure. But after a quick review, the code seems good and already using most of Google codestyle :)

**Comment by choyiny** [comment]
Please see #14 @andreybleme 
It would be great if you could review all of them rather than most!
