### ISSUE TITLE
🎃🍂 CONTRIBUTION.MD

### ISSUE THREAD

**Issue by choyiny** [choyiny/factorizing-semiprimes#16]
Would like someone to create a `CONTRIBUTION.MD` for this project. A few points worthy to mention:
- follow google's java code style
- documentation of code
- when submitting PR make sure it is well outlined/explained
- other points you feel is necessary.

@Wferr claimed

**Comment by Wferr** [comment]
Still open? If so I got this.

**Comment by choyiny** [comment]
@Wferr Yep, open!

**Comment by Wferr** [comment]
Any ideas on improvements is gladly accepted.
