### ISSUE TITLE
🎃🍂 Use BigIntegers class to run algorithms

### ISSUE THREAD

**Issue by choyiny** [choyiny/factorizing-semiprimes#3]
Create a new function to implement Fermat's Factorisation Method, Brute Force Method or Pho's Rollard method with BigIntegers.

See `Main.java` for current implementation without BigIntegers.
- [x] Brute Force #10 
- [x] Fermat's Factorization Method
- [x] Pho's Rollard Method #18 
- [ ] Some other factorization method? #15 

Unticked ones are not claimed.

**Comment by singh1114** [comment]
Review the PR.

**Comment by richa-coder** [comment]
Hey, I can do this.Is it already assigned to somebody?

**Comment by choyiny** [comment]
@richa-coder brute force has been done already. Fermat's Factorization Method and Pho's Rollard Method left.

**Comment by richa-coder** [comment]
okay,i will do it then

[image: --]

Richa Singh
[image: https://]about.me/richa-singh
https://about.me/richa-singh?promo=email_sig&utm_source=email_sig&utm_medium=email_sig&utm_campaign=external_links

**Comment by aarush22** [comment]
Has the Fermat's Factorization Method already been implemented or can I work on that ?

**Comment by choyiny** [comment]
@aarush22 nope, you can work on it.
