### ISSUE TITLE
🎃🍂 Create a GUI for factorising semiprimes

### ISSUE THREAD

**Issue by choyiny** [choyiny/factorizing-semiprimes#4]
Create a GUI with Java to allow user to input numbers themselves. (@richa-coder)

**Comment by mileschandler** [comment]
Id like to take a spin at this. Would you like a full fledged GUI or will a JInputPane suffice?

**Comment by choyiny** [comment]
@mileschandler Both will be fine!
EDIT: Changed my mind, a full fledged GUI would be awesome!

**Comment by mileschandler** [comment]
Oops just read the EDIT. Well a JOptionPane is a starting point.

**Comment by richa-coder** [comment]
Can i work on it??

**Comment by mileschandler** [comment]
Take over for the GUI.

**Comment by choyiny** [comment]
@richa-coder Sure.

**Comment by richa-coder** [comment]
Okay

[image: --]

Richa Singh
[image: https://]about.me/richa-singh
https://about.me/richa-singh?promo=email_sig&utm_source=email_sig&utm_medium=email_sig&utm_campaign=external_links
