### ISSUE TITLE
🎃🍂 add .gitignore to ignore IntelliJ IDEA's project files

### ISSUE THREAD

**Issue by choyiny** [choyiny/factorizing-semiprimes#5]
Beginner issue for Hacktoberfest! Please let some new contributors have a go at this.

Relevant documentation:
https://git-scm.com/docs/gitignore

**Comment by rohanagarwal94** [comment]
@choyiny i want to take up this issue.

**Comment by henrycity** [comment]
@choyiny: Hello, can I do this one?

**Comment by choyiny** [comment]
@rohanagarwal94 do .gitignore for IntelliJ

@tvtri96 do .gitignore for eclipse and other popular java IDEs
